/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PascalController;

/**
 *
 * @author esteb
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    PascalController pascalC;
    public Main() {
        initComponents();
        pascalC = new PascalController(5);
        triangleFrame.setContentPane(new PascalTriangle(pascalC.getPascalRectangles(),5));
        galtonBoardFrame.setContentPane(new GaltonBoard(5));
    }
    private void changeRows(int rows){
        //To do 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PascalPanel = new javax.swing.JPanel();
        rowsLabelPascal = new javax.swing.JLabel();
        rowsSpinerPascal = new javax.swing.JSpinner();
        generateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        triangleFrame = new javax.swing.JInternalFrame();
        GaltonPanel = new javax.swing.JPanel();
        rowsLabelGalton = new javax.swing.JLabel();
        simulateButton = new javax.swing.JButton();
        probabilitySpiner = new javax.swing.JSpinner();
        probabilityLabel = new javax.swing.JLabel();
        rowsSpinerGalton = new javax.swing.JSpinner();
        galtonBoardFrame = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rowsLabelPascal.setText("Rows:");

        rowsSpinerPascal.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        triangleFrame.setVisible(true);

        javax.swing.GroupLayout triangleFrameLayout = new javax.swing.GroupLayout(triangleFrame.getContentPane());
        triangleFrame.getContentPane().setLayout(triangleFrameLayout);
        triangleFrameLayout.setHorizontalGroup(
            triangleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        triangleFrameLayout.setVerticalGroup(
            triangleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PascalPanelLayout = new javax.swing.GroupLayout(PascalPanel);
        PascalPanel.setLayout(PascalPanelLayout);
        PascalPanelLayout.setHorizontalGroup(
            PascalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PascalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(triangleFrame)
                .addGap(18, 18, 18)
                .addGroup(PascalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PascalPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PascalPanelLayout.createSequentialGroup()
                        .addComponent(rowsLabelPascal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowsSpinerPascal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PascalPanelLayout.createSequentialGroup()
                        .addComponent(generateButton)
                        .addGap(9, 9, 9))))
        );
        PascalPanelLayout.setVerticalGroup(
            PascalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PascalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PascalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PascalPanelLayout.createSequentialGroup()
                        .addGroup(PascalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rowsLabelPascal)
                            .addComponent(rowsSpinerPascal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(PascalPanelLayout.createSequentialGroup()
                        .addComponent(triangleFrame)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Pascal Triangle", PascalPanel);

        rowsLabelGalton.setText("Rows:");

        simulateButton.setText("Simulate");
        simulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateButtonActionPerformed(evt);
            }
        });

        probabilitySpiner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.1f)));

        probabilityLabel.setText("Probability:");

        rowsSpinerGalton.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        galtonBoardFrame.setMinimumSize(new java.awt.Dimension(100, 500));
        galtonBoardFrame.setPreferredSize(new java.awt.Dimension(600, 600));
        galtonBoardFrame.setVisible(true);

        javax.swing.GroupLayout galtonBoardFrameLayout = new javax.swing.GroupLayout(galtonBoardFrame.getContentPane());
        galtonBoardFrame.getContentPane().setLayout(galtonBoardFrameLayout);
        galtonBoardFrameLayout.setHorizontalGroup(
            galtonBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        galtonBoardFrameLayout.setVerticalGroup(
            galtonBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GaltonPanelLayout = new javax.swing.GroupLayout(GaltonPanel);
        GaltonPanel.setLayout(GaltonPanelLayout);
        GaltonPanelLayout.setHorizontalGroup(
            GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GaltonPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(galtonBoardFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GaltonPanelLayout.createSequentialGroup()
                        .addGroup(GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(probabilityLabel)
                            .addComponent(rowsLabelGalton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(probabilitySpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rowsSpinerGalton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        GaltonPanelLayout.setVerticalGroup(
            GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GaltonPanelLayout.createSequentialGroup()
                .addGroup(GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GaltonPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rowsLabelGalton)
                            .addComponent(rowsSpinerGalton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GaltonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(probabilitySpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(probabilityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simulateButton))
                    .addGroup(GaltonPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(galtonBoardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Galton Board", GaltonPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        pascalC.updateTriangleHeight((int) rowsSpinerPascal.getValue());
        triangleFrame.setContentPane(
                new PascalTriangle(pascalC.getPascalRectangles(), 
                (int) rowsSpinerPascal.getValue()));
    }//GEN-LAST:event_generateButtonActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
        galtonBoardFrame.setContentPane(new GaltonBoard((int) rowsSpinerGalton.getValue()));
        System.out.println("Deberia simular un galton board de\n"+rowsSpinerGalton.getValue()
        +probabilitySpiner.getValue());
    }//GEN-LAST:event_simulateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GaltonPanel;
    private javax.swing.JPanel PascalPanel;
    private javax.swing.JInternalFrame galtonBoardFrame;
    private javax.swing.JButton generateButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel probabilityLabel;
    private javax.swing.JSpinner probabilitySpiner;
    private javax.swing.JLabel rowsLabelGalton;
    private javax.swing.JLabel rowsLabelPascal;
    private javax.swing.JSpinner rowsSpinerGalton;
    private javax.swing.JSpinner rowsSpinerPascal;
    private javax.swing.JButton simulateButton;
    private javax.swing.JInternalFrame triangleFrame;
    // End of variables declaration//GEN-END:variables
}
